// Code generated by adl2dsl from DUNE1.ADL subsong 6. DO NOT EDIT.

package main

import (
	"github.com/jebbisson/spice-synth/dsl"
	"github.com/jebbisson/spice-synth/stream"
	"github.com/jebbisson/spice-synth/voice"
)

// Instruments extracted from the ADL file.
var (
	instAdl104default = &voice.Instrument{
		Name: "adl_104.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         7,
			Sustain:       2,
			Release:       6,
			Level:         17,
			Multiply:      0,
			KeyScaleLevel: 1,
			Sustaining:    true,
			Waveform:      1,
		},
		Op2: voice.Operator{
			Attack:     15,
			Decay:      1,
			Sustain:    5,
			Release:    15,
			Level:      0,
			Multiply:   0,
			Sustaining: true,
		},
		Feedback:   4,
		Connection: 0,
	}
	instAdl106default = &voice.Instrument{
		Name: "adl_106.default",
		Op1: voice.Operator{
			Attack:     15,
			Decay:      6,
			Sustain:    7,
			Release:    1,
			Level:      14,
			Multiply:   1,
			Sustaining: true,
		},
		Op2: voice.Operator{
			Attack:     15,
			Decay:      0,
			Sustain:    8,
			Release:    5,
			Level:      0,
			Multiply:   1,
			Tremolo:    true,
			Sustaining: true,
			Waveform:   1,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl137default = &voice.Instrument{
		Name: "adl_137.default",
		Op1: voice.Operator{
			Attack:        1,
			Decay:         1,
			Sustain:       2,
			Release:       1,
			Level:         0,
			Multiply:      1,
			KeyScaleLevel: 1,
			Vibrato:       true,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:     2,
			Decay:      2,
			Sustain:    1,
			Release:    1,
			Level:      0,
			Multiply:   6,
			Tremolo:    true,
			Vibrato:    true,
			Sustaining: true,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl138default = &voice.Instrument{
		Name: "adl_138.default",
		Op1: voice.Operator{
			Attack:     15,
			Decay:      2,
			Sustain:    4,
			Release:    1,
			Level:      17,
			Multiply:   0,
			Sustaining: true,
		},
		Op2: voice.Operator{
			Attack:     15,
			Decay:      5,
			Sustain:    2,
			Release:    1,
			Level:      0,
			Multiply:   0,
			Sustaining: true,
		},
		Feedback:   5,
		Connection: 0,
	}
	instAdl139default = &voice.Instrument{
		Name: "adl_139.default",
		Op1: voice.Operator{
			Attack:       2,
			Decay:        1,
			Sustain:      0,
			Release:      2,
			Level:        50,
			Multiply:     1,
			KeyScaleRate: true,
			Sustaining:   true,
		},
		Op2: voice.Operator{
			Attack:     2,
			Decay:      0,
			Sustain:    15,
			Release:    2,
			Level:      0,
			Multiply:   0,
			Vibrato:    true,
			Sustaining: true,
			Waveform:   3,
		},
		Feedback:   7,
		Connection: 0,
	}
	instAdl141default = &voice.Instrument{
		Name: "adl_141.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         0,
			Sustain:       0,
			Release:       1,
			Level:         7,
			Multiply:      7,
			KeyScaleLevel: 2,
		},
		Op2: voice.Operator{
			Attack:   15,
			Decay:    0,
			Sustain:  0,
			Release:  1,
			Level:    0,
			Multiply: 1,
		},
		Feedback:   2,
		Connection: 0,
	}
	instAdl146default = &voice.Instrument{
		Name: "adl_146.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         4,
			Sustain:       5,
			Release:       3,
			Level:         8,
			Multiply:      1,
			KeyScaleRate:  true,
			KeyScaleLevel: 2,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:       15,
			Decay:        2,
			Sustain:      2,
			Release:      7,
			Level:        0,
			Multiply:     0,
			KeyScaleRate: true,
			Sustaining:   true,
			Waveform:     3,
		},
		Feedback:   3,
		Connection: 0,
	}
	instAdl147default = &voice.Instrument{
		Name: "adl_147.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         2,
			Sustain:       2,
			Release:       3,
			Level:         8,
			Multiply:      1,
			KeyScaleLevel: 2,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:     1,
			Decay:      1,
			Sustain:    4,
			Release:    7,
			Level:      0,
			Multiply:   0,
			Sustaining: true,
			Waveform:   3,
		},
		Feedback:   3,
		Connection: 0,
	}
	instAdl148default = &voice.Instrument{
		Name: "adl_148.default",
		Op1: voice.Operator{
			Attack:        2,
			Decay:         10,
			Sustain:       0,
			Release:       2,
			Level:         23,
			Multiply:      7,
			KeyScaleRate:  true,
			KeyScaleLevel: 2,
			Tremolo:       true,
			Vibrato:       true,
		},
		Op2: voice.Operator{
			Attack:       4,
			Decay:        2,
			Sustain:      15,
			Release:      3,
			Level:        0,
			Multiply:     3,
			KeyScaleRate: true,
			Tremolo:      true,
			Vibrato:      true,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl149default = &voice.Instrument{
		Name: "adl_149.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         2,
			Sustain:       5,
			Release:       1,
			Level:         8,
			Multiply:      1,
			KeyScaleRate:  true,
			KeyScaleLevel: 2,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:       15,
			Decay:        2,
			Sustain:      2,
			Release:      1,
			Level:        0,
			Multiply:     0,
			KeyScaleRate: true,
			Sustaining:   true,
			Waveform:     3,
		},
		Feedback:   3,
		Connection: 0,
	}
	instAdl151default = &voice.Instrument{
		Name: "adl_151.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         7,
			Sustain:       13,
			Release:       0,
			Level:         27,
			Multiply:      12,
			KeyScaleRate:  true,
			KeyScaleLevel: 1,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         3,
			Sustain:       5,
			Release:       1,
			Level:         0,
			Multiply:      8,
			KeyScaleRate:  true,
			KeyScaleLevel: 1,
			Sustaining:    true,
		},
		Feedback:   7,
		Connection: 0,
	}
	instAdl152default = &voice.Instrument{
		Name: "adl_152.default",
		Op1: voice.Operator{
			Attack:        4,
			Decay:         15,
			Sustain:       0,
			Release:       7,
			Level:         0,
			Multiply:      0,
			KeyScaleRate:  true,
			KeyScaleLevel: 3,
			Waveform:      2,
		},
		Op2: voice.Operator{
			Attack:     4,
			Decay:      15,
			Sustain:    0,
			Release:    7,
			Level:      0,
			Multiply:   4,
			Sustaining: true,
			Waveform:   3,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl154default = &voice.Instrument{
		Name: "adl_154.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         5,
			Sustain:       0,
			Release:       1,
			Level:         0,
			Multiply:      1,
			KeyScaleLevel: 2,
			Tremolo:       true,
			Vibrato:       true,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:   15,
			Decay:    6,
			Sustain:  0,
			Release:  4,
			Level:    0,
			Multiply: 0,
			Tremolo:  true,
			Vibrato:  true,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl155default = &voice.Instrument{
		Name: "adl_155.default",
		Op1: voice.Operator{
			Attack:     12,
			Decay:      4,
			Sustain:    0,
			Release:    7,
			Level:      0,
			Multiply:   0,
			Tremolo:    true,
			Vibrato:    true,
			Sustaining: true,
		},
		Op2: voice.Operator{
			Attack:   15,
			Decay:    6,
			Sustain:  0,
			Release:  2,
			Level:    0,
			Multiply: 0,
			Vibrato:  true,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl157default = &voice.Instrument{
		Name: "adl_157.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         0,
			Sustain:       2,
			Release:       0,
			Level:         1,
			Multiply:      14,
			KeyScaleLevel: 3,
			Sustaining:    true,
			Waveform:      2,
		},
		Op2: voice.Operator{
			Attack:     15,
			Decay:      2,
			Sustain:    2,
			Release:    3,
			Level:      0,
			Multiply:   12,
			Sustaining: true,
			Waveform:   3,
		},
		Feedback:   7,
		Connection: 0,
	}
	instAdl158default = &voice.Instrument{
		Name: "adl_158.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         15,
			Sustain:       0,
			Release:       1,
			Level:         27,
			Multiply:      4,
			KeyScaleLevel: 3,
			Vibrato:       true,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         3,
			Sustain:       6,
			Release:       2,
			Level:         0,
			Multiply:      14,
			KeyScaleRate:  true,
			KeyScaleLevel: 3,
			Sustaining:    true,
		},
		Feedback:   2,
		Connection: 0,
	}
	instAdl159default = &voice.Instrument{
		Name: "adl_159.default",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         15,
			Sustain:       0,
			Release:       15,
			Level:         0,
			Multiply:      14,
			KeyScaleRate:  true,
			KeyScaleLevel: 1,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:       15,
			Decay:        7,
			Sustain:      12,
			Release:      8,
			Level:        0,
			Multiply:     14,
			KeyScaleRate: true,
			Sustaining:   true,
		},
		Feedback:   7,
		Connection: 0,
	}
)

// Note-start overrides hoisted from repeated ADL events.
var (
	ov0 = dsl.Override().Op2(dsl.OpOverride().Level(10)).Build()
	ov1 = dsl.Override().Op2(dsl.OpOverride().Level(13)).Build()
	ov2 = dsl.Override().Op2(dsl.OpOverride().Level(19)).Build()
	ov3 = dsl.Override().Op2(dsl.OpOverride().Level(25)).Build()
	ov4 = dsl.Override().Op2(dsl.OpOverride().Level(16)).Build()
	ov5 = dsl.Override().Op2(dsl.OpOverride().Level(38)).Build()
	ov6 = dsl.Override().Op2(dsl.OpOverride().Level(32)).Build()
	ov7 = dsl.Override().Op2(dsl.OpOverride().Level(57)).Build()
	ov8 = dsl.Override().Op2(dsl.OpOverride().Level(44)).Build()
)

// NewDUNE1Song6 creates the song from DUNE1 subsong 6.
// BPM: 1080 (1 DSL tick = 1 ADL 72Hz tick)
// Duration: 18305 ticks (254.2 seconds)
// Channels: [0 1 2 3 4 5]
func NewDUNE1Song6() *dsl.Song {
	song := dsl.NewSong(1080)

	// Register instruments
	song.AddInstrument(instAdl104default)
	song.AddInstrument(instAdl106default)
	song.AddInstrument(instAdl137default)
	song.AddInstrument(instAdl138default)
	song.AddInstrument(instAdl139default)
	song.AddInstrument(instAdl141default)
	song.AddInstrument(instAdl146default)
	song.AddInstrument(instAdl147default)
	song.AddInstrument(instAdl148default)
	song.AddInstrument(instAdl149default)
	song.AddInstrument(instAdl151default)
	song.AddInstrument(instAdl152default)
	song.AddInstrument(instAdl154default)
	song.AddInstrument(instAdl155default)
	song.AddInstrument(instAdl157default)
	song.AddInstrument(instAdl158default)
	song.AddInstrument(instAdl159default)

	// Channel 0
	ch0 := dsl.NewTrack(0).
		SetInstrument("adl_104.default").
		SetLength(18305)
	ch0c := ch0.At(0)
	ch0c = ch0c.
		UseOverride(ov0).
		Note("F#2", 17)
	ch0c = ch0c.
		WithRepeat().
		Note("F#2", 19).
		Note("F#2", 18).
		Note("F#2", 18).
		Note("F#2", 18).
		Note("F#2", 19).
		Note("F#2", 18).
		Note("F#2", 18).
		Times(2)
	ch0c = ch0c.
		Note("F#2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("E2", 18).
		Note("E2", 18).
		Note("E2", 18).
		Note("E2", 19).
		Note("E2", 18).
		Note("E2", 18).
		Note("E2", 19).
		Times(2)
	ch0c = ch0c.
		WithRepeat().
		Note("E2", 18).
		Times(2)
	ch0c = ch0c.
		WithRepeat().
		Note("F#2", 18).
		Note("F#2", 19).
		Note("F#2", 18).
		Note("F#2", 18).
		Note("F#2", 19).
		Note("F#2", 18).
		Note("F#2", 18).
		Times(2)
	ch0c = ch0c.
		Note("F#2", 18).
		Note("F#2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("E2", 18).
		Note("E2", 18).
		Note("E2", 19).
		Note("E2", 18).
		Note("E2", 18).
		Note("E2", 18).
		Note("E2", 19).
		Times(2)
	ch0c = ch0c.
		WithRepeat().
		Note("E2", 18).
		Times(2)
	ch0c = ch0c.
		WithRepeat().
		Note("D#2", 9).
		Note("D#2", 10).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 10).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 10).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Times(3)
	ch0c = ch0c.
		Note("D#2", 9)
	ch0c = ch0c.
		WithRepeat().
		Note("D2", 10).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 10).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 10).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Times(3)
	ch0c = ch0c.
		Note("D2", 10)
	ch0c = ch0c.
		WithRepeat().
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 10).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 10).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 9).
		Note("D#2", 10).
		Times(3)
	ch0c = ch0c.
		Note("D#2", 9)
	ch0c = ch0c.
		WithRepeat().
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 10).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 10).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 9).
		Note("D2", 10).
		Note("D2", 9).
		Times(3)
	ch0c = ch0c.
		On("D2").
		Advance(9).
		ChangeInstrument("adl_138.default").
		Off().
		UseOverride(ov1).
		Note("C#2", 20)
	ch0c = ch0c.
		AdvanceTo(3632).
		WithRepeat().
		UseOverride(ov2).
		Note("C#2", 20).
		Times(2)
	ch0c = ch0c.
		AdvanceTo(3835).
		UseOverride(ov3).
		Note("C#2", 23).
		Advance(342).
		Note("C#2", 30).
		Advance(456).
		Note("C#2", 37)
	ch0c = ch0c.
		AdvanceTo(5272).
		WithRepeat().
		Note("C#2", 46).
		Times(2)
	ch0c = ch0c.
		AdvanceTo(6739).
		ChangeInstrument("adl_104.default").
		UseOverride(ov4).
		Note("B2", 78).
		Note("B2", 26).
		Note("B2", 104).
		Note("C#3", 78).
		Note("C#3", 26).
		Note("C#3", 104).
		Note("B2", 78).
		Note("B2", 26).
		Note("B2", 105).
		Note("G#2", 78).
		Note("G#2", 26).
		Note("G#2", 104).
		Note("A2", 78).
		Note("A2", 26).
		Note("A2", 104).
		Note("E2", 78).
		Note("E2", 25).
		Note("E2", 102).
		Note("G#2", 75).
		Note("G#2", 25).
		Note("G#2", 99).
		Note("C#2", 381).
		Note("E2", 360).
		Note("F#2", 353).
		Note("C#2", 341).
		Note("C2", 334).
		Note("C#2", 164).
		Note("E2", 82).
		Note("C2", 82).
		Note("C#2", 164).
		Note("F#2", 164).
		Note("C#2", 327).
		Advance(2686).
		UseOverride(ov5).
		Note("C#2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		UseOverride(ov6).
		Note("C#2", 18).
		Note("C#2", 9).
		Note("C#2", 10).
		UseOverride(ov3).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		UseOverride(ov2).
		Note("C#2", 18).
		Note("C#2", 10).
		Note("C#2", 9).
		UseOverride(ov1).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		UseOverride(ov0).
		Note("C#2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18).
		Note("C#2", 9).
		Note("C#2", 10).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18).
		Note("C#2", 10).
		Note("C#2", 9).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("A2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("A2", 9).
		Times(2)
	ch0c = ch0c.
		Note("A2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("A2", 9).
		Times(2)
	ch0c = ch0c.
		Note("A2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("A2", 9).
		Times(2)
	ch0c = ch0c.
		Note("A2", 18).
		Note("A2", 9).
		Note("A2", 10).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18).
		Note("C#2", 10)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Note("C#2", 18).
		Note("C#2", 9).
		Note("C#2", 9).
		Note("C#2", 19).
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 9).
		Note("C#2", 18).
		Note("C#2", 9).
		Note("C#2", 10).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18).
		Note("C#2", 10).
		Note("C#2", 9).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("A2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("A2", 9).
		Times(2)
	ch0c = ch0c.
		Note("A2", 18).
		Note("A2", 9).
		Note("A2", 10).
		Note("A2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("A2", 9).
		Times(2)
	ch0c = ch0c.
		Note("A2", 18).
		Note("A2", 10).
		Note("A2", 9)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 18).
		Note("C#2", 9).
		Note("C#2", 9).
		Note("C#2", 19).
		Note("C#2", 9).
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18).
		Note("C#2", 9).
		Note("C#2", 10).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18).
		Note("C#2", 10)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Note("C#2", 18).
		Note("C#2", 9).
		Note("C#2", 9).
		Note("C#2", 19).
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 9).
		Note("C#2", 18).
		Note("C#2", 9).
		Note("C#2", 10).
		Note("A2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("A2", 9).
		Times(2)
	ch0c = ch0c.
		Note("A2", 18).
		Note("A2", 10).
		Note("A2", 9).
		Note("A2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("A2", 9).
		Times(2)
	ch0c = ch0c.
		Note("A2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("A2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18).
		Note("C#2", 9).
		Note("C#2", 10).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18).
		Note("C#2", 10).
		Note("C#2", 9).
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C#2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C#2", 9).
		Times(2)
	ch0c = ch0c.
		Note("C3", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("C3", 9).
		Times(2)
	ch0c = ch0c.
		Note("C3", 18).
		Note("C3", 9).
		Note("C3", 10).
		Note("C3", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("C3", 9).
		Times(2)
	ch0c = ch0c.
		Note("C3", 18).
		Note("C3", 10).
		Note("C3", 9)
	ch0c = ch0c.
		WithRepeat().
		Note("D3", 18).
		Note("D3", 9).
		Note("D3", 9).
		Note("D3", 19).
		Note("D3", 9).
		Note("D3", 9).
		Times(2)
	ch0c = ch0c.
		WithRepeat().
		Note("B2", 18).
		Note("B2", 19).
		Note("B2", 18).
		Note("B2", 18).
		Note("B2", 18).
		Note("B2", 19).
		Note("B2", 18).
		Times(2)
	ch0c = ch0c.
		Note("B2", 18).
		Note("B2", 19).
		ClearOverride().
		Note("B2", 18)
	ch0c = ch0c.
		WithRepeat().
		UseOverride(ov0).
		Note("B2", 18).
		Note("B2", 18).
		Note("B2", 19).
		Times(2)
	ch0c = ch0c.
		Note("B2", 18).
		ClearOverride().
		Note("B2", 18)
	ch0c = ch0c.
		WithRepeat().
		UseOverride(ov0).
		Note("B2", 18).
		Note("B2", 19).
		Note("B2", 18).
		Times(2)
	ch0c = ch0c.
		Note("B2", 18).
		ClearOverride().
		Note("B2", 18)
	ch0c = ch0c.
		WithRepeat().
		UseOverride(ov0).
		Note("B2", 19).
		Note("B2", 18).
		Note("B2", 18).
		Times(2)
	ch0c = ch0c.
		Note("B2", 18).
		ClearOverride().
		Note("B2", 19)
	ch0c = ch0c.
		WithRepeat().
		UseOverride(ov0).
		Note("B2", 18).
		Times(2)
	ch0c = ch0c.
		Note("B2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("B2", 18).
		Times(3)
	ch0c = ch0c.
		Note("B2", 19).
		ClearOverride().
		Note("B2", 18).
		UseOverride(ov0).
		Note("B2", 18).
		Note("B2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("B2", 18).
		Times(3)
	ch0c = ch0c.
		Note("B2", 19).
		Note("B2", 18).
		ClearOverride().
		Note("B2", 18).
		UseOverride(ov0).
		Note("B2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("B2", 18).
		Times(3)
	ch0c = ch0c.
		Note("B2", 19)
	ch0c = ch0c.
		WithRepeat().
		Note("B2", 18).
		Times(2)
	ch0c = ch0c.
		ClearOverride().
		Note("B2", 19).
		UseOverride(ov0).
		Note("B2", 18)
	ch0c = ch0c.
		WithRepeat().
		Note("B2", 18).
		Note("B2", 18).
		Note("B2", 19).
		Times(2)
	ch0c = ch0c.
		ClearOverride().
		Note("B2", 18)
	ch0c = ch0c.
		WithRepeat().
		UseOverride(ov0).
		Note("B2", 18).
		Note("B2", 18).
		Note("B2", 19).
		Times(2)
	ch0c = ch0c.
		Note("B2", 18).
		ClearOverride().
		Note("B2", 18)
	ch0c = ch0c.
		WithRepeat().
		UseOverride(ov0).
		Note("B2", 18).
		Note("B2", 19).
		Note("B2", 18).
		Times(2)
	ch0c = ch0c.
		Note("B2", 18).
		ClearOverride().
		Note("B2", 18)
	ch0c = ch0c.
		WithRepeat().
		UseOverride(ov0).
		Note("B2", 19).
		Note("B2", 18).
		Note("B2", 18).
		Times(2)
	ch0c = ch0c.
		Note("B2", 18).
		Advance(293).
		Off().
		Advance(293).
		Off().
		Off()
	song.AddTrack(ch0)

	// Channel 1
	ch1 := dsl.NewTrack(1).
		SetInstrument("adl_139.default").
		SetLength(18305)
	ch1c := ch1.At(0)
	ch1c = ch1c.
		UseOverride(ov3).
		Note("A3", 255).
		Advance(37).
		Note("G3", 292).
		Note("A3", 256).
		Advance(37).
		Note("G3", 292).
		Note("F#3", 147).
		Advance(438).
		Note("F3", 147).
		Advance(439).
		Note("F#4", 438).
		Advance(147).
		Note("F4", 439).
		Advance(471).
		Note("C#3", 183).
		Advance(182).
		Note("D#3", 243).
		Advance(243).
		Note("G#3", 293).
		Advance(293).
		Note("A2", 367).
		Advance(366).
		Note("C3", 184).
		Advance(183).
		Note("C#2", 184).
		Advance(183).
		ChangeInstrument("adl_146.default").
		Advance(209).
		UseOverride(ov4).
		Note("C#1", 416).
		On("G#1").
		Advance(208).
		ChangeInstrument("adl_147.default").
		Off().
		UseOverride(ov3).
		Note("C3", 209).
		Note("G2", 204).
		Note("B2", 199).
		Note("C#3", 289).
		Advance(92).
		Note("B2", 361).
		Note("C#3", 352).
		Note("G#2", 341).
		Note("G2", 335).
		Note("G#2", 163).
		Note("B2", 82).
		Note("G#2", 82).
		Note("G#2", 164).
		Note("C#3", 164).
		Note("G#2", 328).
		Note("C#1", 2231).
		Advance(154).
		ChangeInstrument("adl_139.default").
		Note("D#3", 151).
		Advance(150).
		Note("G#3", 146).
		Advance(146).
		ChangeInstrument("adl_148.default").
		UseOverride(ov5).
		Note("C#4", 9).
		Note("G#4", 10).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 9).
		Note("D#5", 9).
		Note("C#5", 9).
		Note("G#4", 9).
		Note("C#4", 10).
		Note("G#4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 9).
		Note("D#5", 9).
		Note("C#5", 9).
		Note("G#4", 10).
		Note("C#4", 9).
		Note("A4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 9).
		Note("D#5", 9).
		Note("C#5", 10).
		Note("A4", 9).
		Note("C#4", 9).
		Note("A4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 9).
		Note("D#5", 10).
		Note("C#5", 9).
		Note("A4", 9).
		Note("G#4", 9).
		Advance(283).
		Note("C#4", 10).
		Note("G#4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 9).
		Note("D#5", 9).
		Note("C#5", 9).
		Note("G#4", 10).
		Note("C#4", 9).
		Note("G#4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 9).
		Note("D#5", 9).
		Note("C#5", 10).
		Note("G#4", 9).
		Note("C#4", 9).
		Note("A4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 9).
		Note("D#5", 10).
		Note("C#5", 9).
		Note("A4", 9).
		Note("C#4", 9).
		Note("A4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 10).
		Note("D#5", 9).
		Note("C#5", 9).
		Note("A4", 9).
		Note("G#4", 9).
		Advance(284).
		Note("C#4", 9).
		Note("G#4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 9).
		Note("D#5", 9).
		Note("C#5", 10).
		Note("G#4", 9).
		Note("C#4", 9).
		Note("G#4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 9).
		Note("D#5", 10).
		Note("C#5", 9).
		Note("G#4", 9).
		Note("C#4", 9).
		Note("A4", 9).
		Note("C#5", 9).
		Note("D#5", 9).
		Note("E5", 10).
		Note("D#5", 9).
		Note("C#5", 9).
		Note("A4", 9).
		Note("C#4", 9).
		Note("A4", 9).
		Note("C#5", 9).
		Note("D#5", 10).
		Note("E5", 9).
		Note("D#5", 9).
		Note("C#5", 9).
		Note("A4", 9).
		Note("G#4", 9).
		Advance(284).
		Note("C4", 9).
		Note("G4", 9).
		Note("C5", 9).
		Note("D5", 9).
		Note("D#5", 9).
		Note("D5", 10).
		Note("C5", 9).
		Note("G4", 9).
		Note("C4", 9).
		Note("G4", 9).
		Note("C5", 9).
		Note("D5", 9).
		Note("D#5", 10).
		Note("D5", 9).
		Note("C5", 9).
		Note("G4", 9).
		Note("F#4", 9).
		Note("D5", 9).
		Note("F#5", 9).
		Note("G#5", 10).
		Note("A5", 9).
		Note("G#5", 9).
		Note("F#5", 9).
		Note("D5", 9).
		Note("F#4", 9).
		Note("D5", 9).
		Note("F#5", 10).
		Note("G#5", 9).
		Note("A5", 9).
		Note("G#5", 9).
		Note("F#5", 9).
		On("D5").
		Advance(9).
		ChangeInstrument("adl_139.default").
		Off().
		Note("D4", 147).
		Advance(292).
		ChangeInstrument("adl_149.default").
		Advance(146).
		ChangeInstrument("adl_139.default").
		UseOverride(ov6).
		On("F#4").
		Advance(147).
		ChangeInstrument("adl_149.default").
		Off().
		Note("F#3", 9).
		Advance(137).
		ChangeInstrument("adl_139.default").
		On("G4").
		Advance(146).
		ChangeInstrument("adl_149.default").
		Off().
		Note("G3", 9).
		Advance(138).
		ChangeInstrument("adl_139.default").
		On("F#4").
		Advance(146).
		ChangeInstrument("adl_149.default").
		Off().
		Note("F#3", 9).
		Advance(137).
		ChangeInstrument("adl_139.default").
		On("G4").
		Advance(146).
		ChangeInstrument("adl_149.default").
		Off().
		Note("G3", 10).
		Advance(292).
		Off().
		Off()
	song.AddTrack(ch1)

	// Channel 2
	ch2 := dsl.NewTrack(2).
		SetInstrument("adl_139.default").
		SetLength(18305)
	ch2c := ch2.At(0)
	ch2c = ch2c.
		UseOverride(ov3).
		Note("C#4", 255).
		Advance(37).
		Note("B3", 292).
		Note("C#4", 256).
		Advance(37).
		Note("B3", 292).
		Note("A#3", 147).
		Advance(438).
		Note("A3", 147).
		Advance(439).
		Note("A#4", 146).
		Note("B4", 146).
		Note("A#4", 146).
		Advance(147).
		Note("A4", 146).
		Note("A#4", 146).
		Note("A4", 147).
		Advance(654).
		Note("E3", 182).
		Advance(243).
		Note("F#3", 243).
		Advance(292).
		Note("G#2", 293).
		Advance(367).
		Note("C#3", 367).
		Advance(183).
		Note("C#3", 183).
		Advance(184).
		On("E2").
		Advance(183).
		ChangeInstrument("adl_137.default").
		Off().
		Note("B1", 105).
		Advance(104).
		Note("C#1", 104).
		Advance(104).
		Note("B1", 104).
		Advance(105).
		Note("G#1", 104).
		Advance(104).
		ChangeInstrument("adl_139.default").
		Note("E3", 156).
		Advance(52).
		Note("B2", 154).
		Advance(51).
		Note("D#3", 149).
		Advance(50).
		Note("G#2", 289).
		Advance(452).
		ChangeInstrument("adl_151.default").
		Note("A4", 22).
		Advance(417).
		Note("E4", 21).
		Advance(192).
		Note("B4", 21).
		Advance(21).
		Note("C5", 21).
		Advance(3528).
		ChangeInstrument("adl_139.default").
		Note("E3", 153).
		Advance(152).
		Note("C#3", 149).
		Advance(293).
		Note("E4", 146).
		Note("D#4", 147).
		Advance(292).
		Note("C#4", 73).
		Note("G#3", 73).
		Note("A3", 74).
		Note("F#3", 73).
		Advance(292).
		Note("E4", 147).
		Note("D#4", 146).
		Advance(292).
		Note("C4", 74).
		Note("G3", 73).
		Note("A3", 73).
		Note("D4", 73).
		Note("F#4", 146).
		Advance(293).
		ChangeInstrument("adl_149.default").
		Advance(146).
		ChangeInstrument("adl_139.default").
		UseOverride(ov6).
		On("D4").
		Advance(146).
		ChangeInstrument("adl_149.default").
		Off().
		Note("D3", 10).
		Advance(137).
		ChangeInstrument("adl_139.default").
		On("C#4").
		Advance(146).
		ChangeInstrument("adl_149.default").
		Off().
		Note("C#3", 9).
		Advance(137).
		ChangeInstrument("adl_139.default").
		On("D4").
		Advance(147).
		ChangeInstrument("adl_149.default").
		Off().
		Note("D3", 9).
		Advance(137).
		ChangeInstrument("adl_139.default").
		On("C#4").
		Advance(146).
		ChangeInstrument("adl_149.default").
		Off().
		Note("C#3", 9).
		Advance(293).
		Off().
		Off()
	song.AddTrack(ch2)

	// Channel 3
	ch3 := dsl.NewTrack(3).
		SetInstrument("adl_152.default").
		SetLength(18305)
	ch3c := ch3.At(0)
	ch3c = ch3c.
		AdvanceTo(584).
		UseOverride(ov6).
		Note("C#4", 293).
		On("B3").
		Advance(292).
		ChangeInstrument("adl_106.default").
		Off()
	ch3c = ch3c.
		WithRepeat().
		UseOverride(ov3).
		Note("A#2", 9).
		Note("A#2", 10).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 10).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 10).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Times(3)
	ch3c = ch3c.
		Note("A#2", 9)
	ch3c = ch3c.
		WithRepeat().
		Note("A2", 10).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 10).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 10).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Times(3)
	ch3c = ch3c.
		Note("A2", 10)
	ch3c = ch3c.
		WithRepeat().
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 10).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 10).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 9).
		Note("A#2", 10).
		Times(3)
	ch3c = ch3c.
		Note("A#2", 9)
	ch3c = ch3c.
		WithRepeat().
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 10).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 10).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 9).
		Note("A2", 10).
		Note("A2", 9).
		Times(3)
	ch3c = ch3c.
		Note("A2", 9).
		Advance(163).
		ChangeInstrument("adl_154.default").
		UseOverride(ov7).
		Note("A6", 10).
		Note("G#6", 10).
		Note("G6", 10).
		Note("F#6", 10).
		Note("F6", 10).
		Note("E6", 11).
		Note("D#6", 10).
		Note("D6", 10).
		Note("C#6", 10).
		Note("C6", 10).
		Note("B5", 11).
		Note("A#5", 10).
		Note("A5", 10).
		Note("G#5", 10).
		Note("G5", 10).
		Note("F#5", 10).
		Advance(228).
		Note("A6", 11).
		Advance(80).
		Note("G6", 11).
		Advance(156).
		Note("A6", 15).
		Advance(167).
		Note("G#6", 15).
		Advance(241).
		Note("E6", 18).
		Advance(274).
		Note("D#6", 19).
		Advance(476).
		Note("B5", 23).
		Advance(252).
		Note("A#6", 23).
		Advance(160).
		Note("A6", 23).
		Advance(619).
		Note("F6", 23).
		Advance(69).
		UseOverride(ov5).
		Note("B4", 14).
		Advance(91).
		Note("D#5", 13).
		Advance(39).
		Note("E5", 13).
		Advance(39).
		Note("C#5", 13).
		Advance(91).
		Note("G#4", 13).
		Advance(91).
		Note("A4", 13).
		Advance(91).
		Note("G#4", 13).
		Advance(39).
		Note("F#4", 13).
		Advance(39).
		Note("D#4", 14).
		Advance(91).
		Note("E4", 13).
		Advance(39).
		Note("D#4", 13).
		Advance(39).
		ChangeInstrument("adl_155.default").
		UseOverride(ov6).
		Note("C4", 208).
		Note("B3", 205).
		Note("B3", 199).
		Note("C#4", 381).
		Note("G3", 360).
		Note("F#3", 353).
		Note("E3", 341).
		Note("D#3", 334).
		Note("C#3", 164).
		Note("E3", 82).
		Note("D#3", 82).
		Note("C#3", 164).
		Note("A3", 164).
		Note("E3", 163).
		Note("D#3", 164).
		Note("C#2", 489).
		Advance(401).
		Note("G#2", 161).
		Advance(80).
		Note("C#3", 238).
		Advance(79).
		Note("D3", 315).
		Advance(158).
		Note("B2", 311).
		Note("C#2", 305).
		Advance(442).
		ChangeInstrument("adl_141.default").
		Note("G#4", 9).
		Advance(576).
		Note("E5", 9).
		Advance(64).
		Note("G#5", 9).
		Advance(64).
		Note("A5", 9).
		Advance(430).
		Note("G#4", 9).
		Advance(137).
		Note("D#5", 10).
		Advance(429).
		Note("D#5", 9).
		Advance(64).
		Note("G5", 10).
		Advance(64).
		Note("D5", 9).
		Advance(137).
		Note("B5", 9).
		Advance(576).
		ChangeInstrument("adl_149.default").
		Advance(146).
		Note("B3", 9).
		Advance(284).
		UseOverride(ov3).
		Note("C#4", 9).
		Advance(283).
		UseOverride(ov6).
		Note("B3", 10).
		Advance(283).
		UseOverride(ov3).
		Note("C#4", 9).
		Advance(293).
		Off().
		Off()
	song.AddTrack(ch3)

	// Channel 4
	ch4 := dsl.NewTrack(4).
		SetInstrument("adl_157.default").
		SetLength(18305)
	ch4c := ch4.At(0)
	ch4c = ch4c.
		AdvanceTo(566).
		WithRepeat().
		UseOverride(ov8).
		Note("C4", 9).
		UseOverride(ov5).
		Note("C4", 9).
		UseOverride(ov3).
		Note("C4", 9).
		Times(2)
	ch4c = ch4c.
		AdvanceTo(1754).
		Note("C4", 10)
	ch4c = ch4c.
		AdvanceTo(2340).
		WithRepeat().
		Note("C4", 9).
		Times(2)
	ch4c = ch4c.
		AdvanceTo(6738).
		ChangeInstrument("adl_158.default").
		Note("G0", 14).
		Advance(403).
		UseOverride(ov1).
		Note("G0", 13).
		Advance(404).
		ChangeInstrument("adl_159.default")
	ch4c = ch4c.
		WithRepeat().
		UseOverride(ov5).
		Note("C4", 13).
		Times(11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 13).
		Times(2)
	ch4c = ch4c.
		Note("C4", 12)
	ch4c = ch4c.
		AdvanceTo(7934).
		WithRepeat().
		Note("C4", 13).
		Times(2)
	ch4c = ch4c.
		AdvanceTo(7985).
		WithRepeat().
		Note("C4", 12).
		Advance(13).
		Note("C4", 12).
		Advance(13).
		Note("C4", 12).
		Times(2)
	ch4c = ch4c.
		Note("C4", 13)
	ch4c = ch4c.
		AdvanceTo(8159).
		WithRepeat().
		Note("C4", 12).
		Times(2)
	ch4c = ch4c.
		Note("C4", 12).
		Note("C4", 13)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 12).
		Advance(12).
		Note("C4", 12).
		Advance(12).
		Note("C4", 12).
		Advance(12).
		Note("C4", 12).
		Advance(12).
		Note("C4", 12).
		Note("C4", 12).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		Note("C4", 12).
		Note("C4", 11).
		Advance(12).
		Note("C4", 12)
	ch4c = ch4c.
		AdvanceTo(8565).
		WithRepeat().
		Note("C4", 11).
		Times(3)
	ch4c = ch4c.
		Note("C4", 12).
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Advance(11).
		Note("C4", 12).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Times(3)
	ch4c = ch4c.
		Note("C4", 11).
		Note("C4", 12)
	ch4c = ch4c.
		AdvanceTo(8881).
		WithRepeat().
		Note("C4", 11).
		Times(3)
	ch4c = ch4c.
		Note("C4", 12)
	ch4c = ch4c.
		AdvanceTo(8970).
		WithRepeat().
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		Note("C4", 12)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Advance(11).
		Note("C4", 11).
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Advance(11).
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Times(3)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Advance(11).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Note("C4", 11).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		AdvanceTo(9471).
		Note("C4", 10).
		Note("C4", 11).
		Note("C4", 10)
	ch4c = ch4c.
		AdvanceTo(9513).
		WithRepeat().
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		Note("C4", 10).
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Note("C4", 10).
		Note("C4", 11).
		Note("C4", 10).
		Note("C4", 11).
		Advance(10).
		Note("C4", 11).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 11).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		AdvanceTo(9901).
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 11).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 11).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 11).
		Note("C4", 10)
	ch4c = ch4c.
		AdvanceTo(10199).
		WithRepeat().
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 11).
		Note("C4", 10).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 11).
		Note("C4", 10).
		Note("C4", 10).
		Advance(10).
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 11).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Advance(11).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Advance(11).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 11).
		Note("C4", 10).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 10).
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		AdvanceTo(10977).
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 11).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 10).
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Times(5)
	ch4c = ch4c.
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Times(3)
	ch4c = ch4c.
		Note("C4", 11)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 11)
	ch4c = ch4c.
		AdvanceTo(11425).
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 11).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Times(3)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 9).
		Times(3)
	ch4c = ch4c.
		Note("C4", 10)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 9).
		Times(3)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Times(2)
	ch4c = ch4c.
		Note("C4", 9).
		Note("C4", 10)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 9).
		Times(2)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 10).
		Note("C4", 9).
		Times(2)
	ch4c = ch4c.
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 9).
		Times(2)
	ch4c = ch4c.
		Note("C4", 9).
		Note("C4", 10)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 9).
		Note("C4", 9).
		Note("C4", 9).
		Note("C4", 9).
		Note("C4", 10).
		Note("C4", 9).
		Note("C4", 9).
		Times(5)
	ch4c = ch4c.
		WithRepeat().
		Note("C4", 9).
		Times(2)
	song.AddTrack(ch4)

	// Channel 5
	ch5 := dsl.NewTrack(5).
		SetInstrument("adl_147.default").
		SetLength(18305)
	ch5c := ch5.At(0)
	ch5c = ch5c.
		UseOverride(ov3).
		Note("F#2", 292).
		Note("E2", 292).
		Note("F#2", 293).
		Note("E2", 292).
		Note("D#2", 585).
		Note("D2", 586).
		Note("D#2", 585).
		Note("D2", 585).
		Advance(325).
		ChangeInstrument("adl_137.default").
		Note("C#2", 273).
		Advance(213).
		Note("A1", 243).
		Advance(414).
		Note("C#1", 293).
		Advance(366).
		Note("B0", 184).
		Advance(5925).
		Note("C#1", 321).
		Advance(317).
		Note("G1", 315).
		Advance(3264).
		UseOverride(ov2).
		Note("B1", 292).
		Advance(293).
		Off().
		Off()
	song.AddTrack(ch5)

	return song
}

// PlayDUNE1 creates a stream and plays the song.
// Returns the stream for use with audio output.
func PlayDUNE1(st *stream.Stream) error {
	song := NewDUNE1Song6()
	return song.Play(st)
}
