// Code generated by adl2dsl from DUNE1.ADL subsong 6. DO NOT EDIT.

package main

import (
	"github.com/jebbisson/spice-synth/dsl"
	"github.com/jebbisson/spice-synth/stream"
	"github.com/jebbisson/spice-synth/voice"
)

// Instruments extracted from the ADL file.
var (
	instAdl143 = &voice.Instrument{
		Name: "adl_143",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         7,
			Sustain:       2,
			Release:       6,
			Level:         17,
			Multiply:      0,
			KeyScaleLevel: 1,
			Sustaining:    true,
			Waveform:      1,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         1,
			Sustain:       5,
			Release:       15,
			Level:         0,
			Multiply:      0,
			Sustaining:    true,
		},
		Feedback:   4,
		Connection: 0,
	}
	instAdl144 = &voice.Instrument{
		Name: "adl_144",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         2,
			Sustain:       4,
			Release:       1,
			Level:         17,
			Multiply:      0,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         5,
			Sustain:       2,
			Release:       1,
			Level:         0,
			Multiply:      0,
			Sustaining:    true,
		},
		Feedback:   5,
		Connection: 0,
	}
	instAdl145 = &voice.Instrument{
		Name: "adl_145",
		Op1: voice.Operator{
			Attack:        2,
			Decay:         1,
			Sustain:       0,
			Release:       2,
			Level:         50,
			Multiply:      1,
			KeyScaleRate:  true,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        2,
			Decay:         0,
			Sustain:       15,
			Release:       2,
			Level:         0,
			Multiply:      0,
			Vibrato:       true,
			Sustaining:    true,
			Waveform:      3,
		},
		Feedback:   7,
		Connection: 0,
	}
	instAdl146 = &voice.Instrument{
		Name: "adl_146",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         4,
			Sustain:       5,
			Release:       3,
			Level:         8,
			Multiply:      1,
			KeyScaleRate:  true,
			KeyScaleLevel: 2,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         2,
			Sustain:       2,
			Release:       7,
			Level:         0,
			Multiply:      0,
			KeyScaleRate:  true,
			Sustaining:    true,
			Waveform:      3,
		},
		Feedback:   3,
		Connection: 0,
	}
	instAdl147 = &voice.Instrument{
		Name: "adl_147",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         2,
			Sustain:       2,
			Release:       3,
			Level:         8,
			Multiply:      1,
			KeyScaleLevel: 2,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        1,
			Decay:         1,
			Sustain:       4,
			Release:       7,
			Level:         0,
			Multiply:      0,
			Sustaining:    true,
			Waveform:      3,
		},
		Feedback:   3,
		Connection: 0,
	}
	instAdl148 = &voice.Instrument{
		Name: "adl_148",
		Op1: voice.Operator{
			Attack:        2,
			Decay:         10,
			Sustain:       0,
			Release:       2,
			Level:         23,
			Multiply:      7,
			KeyScaleRate:  true,
			KeyScaleLevel: 2,
			Tremolo:       true,
			Vibrato:       true,
		},
		Op2: voice.Operator{
			Attack:        4,
			Decay:         2,
			Sustain:       15,
			Release:       3,
			Level:         0,
			Multiply:      3,
			KeyScaleRate:  true,
			Tremolo:       true,
			Vibrato:       true,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl149 = &voice.Instrument{
		Name: "adl_149",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         2,
			Sustain:       5,
			Release:       1,
			Level:         8,
			Multiply:      1,
			KeyScaleRate:  true,
			KeyScaleLevel: 2,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         2,
			Sustain:       2,
			Release:       1,
			Level:         0,
			Multiply:      0,
			KeyScaleRate:  true,
			Sustaining:    true,
			Waveform:      3,
		},
		Feedback:   3,
		Connection: 0,
	}
	instAdl150 = &voice.Instrument{
		Name: "adl_150",
		Op1: voice.Operator{
			Attack:        1,
			Decay:         1,
			Sustain:       2,
			Release:       1,
			Level:         0,
			Multiply:      1,
			KeyScaleLevel: 1,
			Vibrato:       true,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        2,
			Decay:         2,
			Sustain:       1,
			Release:       1,
			Level:         0,
			Multiply:      6,
			Tremolo:       true,
			Vibrato:       true,
			Sustaining:    true,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl151 = &voice.Instrument{
		Name: "adl_151",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         7,
			Sustain:       13,
			Release:       0,
			Level:         27,
			Multiply:      12,
			KeyScaleRate:  true,
			KeyScaleLevel: 1,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         3,
			Sustain:       5,
			Release:       1,
			Level:         0,
			Multiply:      8,
			KeyScaleRate:  true,
			KeyScaleLevel: 1,
			Sustaining:    true,
		},
		Feedback:   7,
		Connection: 0,
	}
	instAdl152 = &voice.Instrument{
		Name: "adl_152",
		Op1: voice.Operator{
			Attack:        4,
			Decay:         15,
			Sustain:       0,
			Release:       7,
			Level:         0,
			Multiply:      0,
			KeyScaleRate:  true,
			KeyScaleLevel: 3,
			Waveform:      2,
		},
		Op2: voice.Operator{
			Attack:        4,
			Decay:         15,
			Sustain:       0,
			Release:       7,
			Level:         0,
			Multiply:      4,
			Sustaining:    true,
			Waveform:      3,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl153 = &voice.Instrument{
		Name: "adl_153",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         6,
			Sustain:       7,
			Release:       1,
			Level:         14,
			Multiply:      1,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         0,
			Sustain:       8,
			Release:       5,
			Level:         0,
			Multiply:      1,
			Tremolo:       true,
			Sustaining:    true,
			Waveform:      1,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl154 = &voice.Instrument{
		Name: "adl_154",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         5,
			Sustain:       0,
			Release:       1,
			Level:         0,
			Multiply:      1,
			KeyScaleLevel: 2,
			Tremolo:       true,
			Vibrato:       true,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         6,
			Sustain:       0,
			Release:       4,
			Level:         0,
			Multiply:      0,
			Tremolo:       true,
			Vibrato:       true,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl155 = &voice.Instrument{
		Name: "adl_155",
		Op1: voice.Operator{
			Attack:        12,
			Decay:         4,
			Sustain:       0,
			Release:       7,
			Level:         0,
			Multiply:      0,
			Tremolo:       true,
			Vibrato:       true,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         6,
			Sustain:       0,
			Release:       2,
			Level:         0,
			Multiply:      0,
			Vibrato:       true,
		},
		Feedback:   0,
		Connection: 0,
	}
	instAdl156 = &voice.Instrument{
		Name: "adl_156",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         0,
			Sustain:       0,
			Release:       1,
			Level:         7,
			Multiply:      7,
			KeyScaleLevel: 2,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         0,
			Sustain:       0,
			Release:       1,
			Level:         0,
			Multiply:      1,
		},
		Feedback:   2,
		Connection: 0,
	}
	instAdl157 = &voice.Instrument{
		Name: "adl_157",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         0,
			Sustain:       2,
			Release:       0,
			Level:         1,
			Multiply:      14,
			KeyScaleLevel: 3,
			Sustaining:    true,
			Waveform:      2,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         2,
			Sustain:       2,
			Release:       3,
			Level:         0,
			Multiply:      12,
			Sustaining:    true,
			Waveform:      3,
		},
		Feedback:   7,
		Connection: 0,
	}
	instAdl158 = &voice.Instrument{
		Name: "adl_158",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         15,
			Sustain:       0,
			Release:       1,
			Level:         27,
			Multiply:      4,
			KeyScaleLevel: 3,
			Vibrato:       true,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         3,
			Sustain:       6,
			Release:       2,
			Level:         0,
			Multiply:      14,
			KeyScaleRate:  true,
			KeyScaleLevel: 3,
			Sustaining:    true,
		},
		Feedback:   2,
		Connection: 0,
	}
	instAdl159 = &voice.Instrument{
		Name: "adl_159",
		Op1: voice.Operator{
			Attack:        15,
			Decay:         15,
			Sustain:       0,
			Release:       15,
			Level:         0,
			Multiply:      14,
			KeyScaleRate:  true,
			KeyScaleLevel: 1,
			Sustaining:    true,
		},
		Op2: voice.Operator{
			Attack:        15,
			Decay:         7,
			Sustain:       12,
			Release:       8,
			Level:         0,
			Multiply:      14,
			KeyScaleRate:  true,
			Sustaining:    true,
		},
		Feedback:   7,
		Connection: 0,
	}
)

// NewDUNE1Song6 creates the song from DUNE1 subsong 6.
// BPM: 1080 (1 DSL tick = 1 ADL 72Hz tick)
// Duration: 17719 ticks (246.1 seconds)
// Channels: [0 1 2 3 4 5]
func NewDUNE1Song6() *dsl.Song {
	song := dsl.NewSong(1080)

	// Register instruments
	song.AddInstrument(instAdl143)
	song.AddInstrument(instAdl144)
	song.AddInstrument(instAdl145)
	song.AddInstrument(instAdl146)
	song.AddInstrument(instAdl147)
	song.AddInstrument(instAdl148)
	song.AddInstrument(instAdl149)
	song.AddInstrument(instAdl150)
	song.AddInstrument(instAdl151)
	song.AddInstrument(instAdl152)
	song.AddInstrument(instAdl153)
	song.AddInstrument(instAdl154)
	song.AddInstrument(instAdl155)
	song.AddInstrument(instAdl156)
	song.AddInstrument(instAdl157)
	song.AddInstrument(instAdl158)
	song.AddInstrument(instAdl159)

	// Channel 0
	ch0 := dsl.NewTrack(0)
	ch0.AddEvent(dsl.TrackEvent{Tick: 0, Type: dsl.TrackNoteOn, Note: voice.Note(92.9), NoteStr: "F#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 292, Type: dsl.TrackNoteOn, Note: voice.Note(82.9), NoteStr: "E2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 584, Type: dsl.TrackNoteOn, Note: voice.Note(92.9), NoteStr: "F#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 877, Type: dsl.TrackNoteOn, Note: voice.Note(82.9), NoteStr: "E2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 1169, Type: dsl.TrackNoteOn, Note: voice.Note(78.3), NoteStr: "D#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 1754, Type: dsl.TrackNoteOn, Note: voice.Note(73.8), NoteStr: "D2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 2340, Type: dsl.TrackNoteOn, Note: voice.Note(78.3), NoteStr: "D#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 2925, Type: dsl.TrackNoteOn, Note: voice.Note(73.8), NoteStr: "D2", Instrument: "adl_143"})
	ch0.SetInstrumentAt(3510, "adl_144")
	ch0.AddEvent(dsl.TrackEvent{Tick: 3510, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_144"})
	ch0.NoteOff(3530)
	ch0.AddEvent(dsl.TrackEvent{Tick: 3632, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_144"})
	ch0.NoteOff(3652)
	ch0.AddEvent(dsl.TrackEvent{Tick: 3673, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_144"})
	ch0.NoteOff(3693)
	ch0.AddEvent(dsl.TrackEvent{Tick: 3835, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_144"})
	ch0.NoteOff(3858)
	ch0.AddEvent(dsl.TrackEvent{Tick: 4200, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_144"})
	ch0.NoteOff(4230)
	ch0.AddEvent(dsl.TrackEvent{Tick: 4686, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_144"})
	ch0.NoteOff(4723)
	ch0.AddEvent(dsl.TrackEvent{Tick: 5272, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_144"})
	ch0.NoteOff(5318)
	ch0.AddEvent(dsl.TrackEvent{Tick: 6005, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_144"})
	ch0.NoteOff(6051)
	ch0.SetInstrumentAt(6739, "adl_143")
	ch0.AddEvent(dsl.TrackEvent{Tick: 6739, Type: dsl.TrackNoteOn, Note: voice.Note(124.4), NoteStr: "B2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 6947, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 7155, Type: dsl.TrackNoteOn, Note: voice.Note(124.4), NoteStr: "B2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 7364, Type: dsl.TrackNoteOn, Note: voice.Note(104.5), NoteStr: "G#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 7572, Type: dsl.TrackNoteOn, Note: voice.Note(110.8), NoteStr: "A2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 7780, Type: dsl.TrackNoteOn, Note: voice.Note(82.9), NoteStr: "E2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 7985, Type: dsl.TrackNoteOn, Note: voice.Note(104.5), NoteStr: "G#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 8184, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 8565, Type: dsl.TrackNoteOn, Note: voice.Note(82.9), NoteStr: "E2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 8925, Type: dsl.TrackNoteOn, Note: voice.Note(92.9), NoteStr: "F#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 9278, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 9619, Type: dsl.TrackNoteOn, Note: voice.Note(65.8), NoteStr: "C2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 9953, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 10117, Type: dsl.TrackNoteOn, Note: voice.Note(82.9), NoteStr: "E2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 10199, Type: dsl.TrackNoteOn, Note: voice.Note(65.8), NoteStr: "C2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 10281, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 10445, Type: dsl.TrackNoteOn, Note: voice.Note(92.9), NoteStr: "F#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 10609, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_143"})
	ch0.NoteOff(10936)
	ch0.AddEvent(dsl.TrackEvent{Tick: 13622, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 14061, Type: dsl.TrackNoteOn, Note: voice.Note(110.8), NoteStr: "A2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 14208, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 14646, Type: dsl.TrackNoteOn, Note: voice.Note(110.8), NoteStr: "A2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 14793, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 15232, Type: dsl.TrackNoteOn, Note: voice.Note(110.8), NoteStr: "A2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 15378, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 15670, Type: dsl.TrackNoteOn, Note: voice.Note(131.6), NoteStr: "C3", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 15817, Type: dsl.TrackNoteOn, Note: voice.Note(147.5), NoteStr: "D3", Instrument: "adl_143"})
	ch0.AddEvent(dsl.TrackEvent{Tick: 15963, Type: dsl.TrackNoteOn, Note: voice.Note(124.4), NoteStr: "B2", Instrument: "adl_143"})
	ch0.NoteOff(17718)
	song.AddTrack(ch0)

	// Channel 1
	ch1 := dsl.NewTrack(1)
	ch1.AddEvent(dsl.TrackEvent{Tick: 0, Type: dsl.TrackNoteOn, Note: voice.Note(221.5), NoteStr: "A3", Instrument: "adl_145"})
	ch1.NoteOff(255)
	ch1.AddEvent(dsl.TrackEvent{Tick: 292, Type: dsl.TrackNoteOn, Note: voice.Note(197.2), NoteStr: "G3", Instrument: "adl_145"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 584, Type: dsl.TrackNoteOn, Note: voice.Note(221.5), NoteStr: "A3", Instrument: "adl_145"})
	ch1.NoteOff(840)
	ch1.AddEvent(dsl.TrackEvent{Tick: 877, Type: dsl.TrackNoteOn, Note: voice.Note(197.2), NoteStr: "G3", Instrument: "adl_145"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 1169, Type: dsl.TrackNoteOn, Note: voice.Note(185.9), NoteStr: "F#3", Instrument: "adl_145"})
	ch1.NoteOff(1316)
	ch1.AddEvent(dsl.TrackEvent{Tick: 1754, Type: dsl.TrackNoteOn, Note: voice.Note(175.6), NoteStr: "F3", Instrument: "adl_145"})
	ch1.NoteOff(1901)
	ch1.AddEvent(dsl.TrackEvent{Tick: 2340, Type: dsl.TrackNoteOn, Note: voice.Note(371.7), NoteStr: "F#4", Instrument: "adl_145"})
	ch1.NoteOff(2778)
	ch1.AddEvent(dsl.TrackEvent{Tick: 2925, Type: dsl.TrackNoteOn, Note: voice.Note(351.2), NoteStr: "F4", Instrument: "adl_145"})
	ch1.NoteOff(3364)
	ch1.AddEvent(dsl.TrackEvent{Tick: 3835, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_145"})
	ch1.NoteOff(4018)
	ch1.AddEvent(dsl.TrackEvent{Tick: 4200, Type: dsl.TrackNoteOn, Note: voice.Note(156.7), NoteStr: "D#3", Instrument: "adl_145"})
	ch1.NoteOff(4443)
	ch1.AddEvent(dsl.TrackEvent{Tick: 4686, Type: dsl.TrackNoteOn, Note: voice.Note(209.0), NoteStr: "G#3", Instrument: "adl_145"})
	ch1.NoteOff(4979)
	ch1.AddEvent(dsl.TrackEvent{Tick: 5272, Type: dsl.TrackNoteOn, Note: voice.Note(110.8), NoteStr: "A2", Instrument: "adl_145"})
	ch1.NoteOff(5639)
	ch1.AddEvent(dsl.TrackEvent{Tick: 6005, Type: dsl.TrackNoteOn, Note: voice.Note(131.6), NoteStr: "C3", Instrument: "adl_145"})
	ch1.NoteOff(6189)
	ch1.AddEvent(dsl.TrackEvent{Tick: 6372, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_145"})
	ch1.NoteOff(6556)
	ch1.SetInstrumentAt(6739, "adl_146")
	ch1.AddEvent(dsl.TrackEvent{Tick: 6948, Type: dsl.TrackNoteOn, Note: voice.Note(34.9), NoteStr: "C#1", Instrument: "adl_146"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 7364, Type: dsl.TrackNoteOn, Note: voice.Note(52.2), NoteStr: "G#1", Instrument: "adl_146"})
	ch1.SetInstrumentAt(7572, "adl_147")
	ch1.AddEvent(dsl.TrackEvent{Tick: 7572, Type: dsl.TrackNoteOn, Note: voice.Note(131.6), NoteStr: "C3", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 7781, Type: dsl.TrackNoteOn, Note: voice.Note(98.6), NoteStr: "G2", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 7985, Type: dsl.TrackNoteOn, Note: voice.Note(124.4), NoteStr: "B2", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 8184, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_147"})
	ch1.NoteOff(8473)
	ch1.AddEvent(dsl.TrackEvent{Tick: 8565, Type: dsl.TrackNoteOn, Note: voice.Note(124.4), NoteStr: "B2", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 8926, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 9278, Type: dsl.TrackNoteOn, Note: voice.Note(104.5), NoteStr: "G#2", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 9619, Type: dsl.TrackNoteOn, Note: voice.Note(98.6), NoteStr: "G2", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 9954, Type: dsl.TrackNoteOn, Note: voice.Note(104.5), NoteStr: "G#2", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 10117, Type: dsl.TrackNoteOn, Note: voice.Note(124.4), NoteStr: "B2", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 10199, Type: dsl.TrackNoteOn, Note: voice.Note(104.5), NoteStr: "G#2", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 10445, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 10609, Type: dsl.TrackNoteOn, Note: voice.Note(104.5), NoteStr: "G#2", Instrument: "adl_147"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 10937, Type: dsl.TrackNoteOn, Note: voice.Note(34.9), NoteStr: "C#1", Instrument: "adl_147"})
	ch1.NoteOff(13168)
	ch1.SetInstrumentAt(13322, "adl_145")
	ch1.AddEvent(dsl.TrackEvent{Tick: 13322, Type: dsl.TrackNoteOn, Note: voice.Note(156.7), NoteStr: "D#3", Instrument: "adl_145"})
	ch1.NoteOff(13473)
	ch1.AddEvent(dsl.TrackEvent{Tick: 13623, Type: dsl.TrackNoteOn, Note: voice.Note(209.0), NoteStr: "G#3", Instrument: "adl_145"})
	ch1.NoteOff(13769)
	ch1.SetInstrumentAt(13915, "adl_148")
	ch1.AddEvent(dsl.TrackEvent{Tick: 13915, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 13924, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 13934, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 13943, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 13952, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 13961, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 13970, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 13979, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 13988, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 13998, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14007, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14016, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14025, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14034, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14043, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14052, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14062, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14071, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14080, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14089, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14098, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14107, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14116, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14126, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14135, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14144, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14153, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14162, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14171, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14180, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14190, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14199, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14208, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.NoteOff(14217)
	ch1.AddEvent(dsl.TrackEvent{Tick: 14500, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14510, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14519, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14528, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14537, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14546, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14555, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14564, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14574, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14583, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14592, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14601, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14610, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14619, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14628, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14638, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14647, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14656, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14665, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14674, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14683, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14692, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14702, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14711, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14720, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14729, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14738, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14747, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14756, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14766, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14775, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14784, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 14793, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.NoteOff(14802)
	ch1.AddEvent(dsl.TrackEvent{Tick: 15086, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15095, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15104, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15113, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15122, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15131, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15140, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15150, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15159, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15168, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15177, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15186, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15195, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15204, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15214, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15223, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15232, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15241, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15250, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15259, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15268, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15278, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15287, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15296, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15305, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15314, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15323, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15332, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15342, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15351, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15360, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15369, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15378, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_148"})
	ch1.NoteOff(15387)
	ch1.AddEvent(dsl.TrackEvent{Tick: 15671, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15680, Type: dsl.TrackNoteOn, Note: voice.Note(394.5), NoteStr: "G4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15689, Type: dsl.TrackNoteOn, Note: voice.Note(526.5), NoteStr: "C5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15698, Type: dsl.TrackNoteOn, Note: voice.Note(590.2), NoteStr: "D5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15707, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15716, Type: dsl.TrackNoteOn, Note: voice.Note(590.2), NoteStr: "D5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15726, Type: dsl.TrackNoteOn, Note: voice.Note(526.5), NoteStr: "C5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15735, Type: dsl.TrackNoteOn, Note: voice.Note(394.5), NoteStr: "G4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15744, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15753, Type: dsl.TrackNoteOn, Note: voice.Note(394.5), NoteStr: "G4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15762, Type: dsl.TrackNoteOn, Note: voice.Note(526.5), NoteStr: "C5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15771, Type: dsl.TrackNoteOn, Note: voice.Note(590.2), NoteStr: "D5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15780, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15790, Type: dsl.TrackNoteOn, Note: voice.Note(590.2), NoteStr: "D5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15799, Type: dsl.TrackNoteOn, Note: voice.Note(526.5), NoteStr: "C5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15808, Type: dsl.TrackNoteOn, Note: voice.Note(394.5), NoteStr: "G4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15817, Type: dsl.TrackNoteOn, Note: voice.Note(371.7), NoteStr: "F#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15826, Type: dsl.TrackNoteOn, Note: voice.Note(590.2), NoteStr: "D5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15835, Type: dsl.TrackNoteOn, Note: voice.Note(743.4), NoteStr: "F#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15844, Type: dsl.TrackNoteOn, Note: voice.Note(836.0), NoteStr: "G#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15854, Type: dsl.TrackNoteOn, Note: voice.Note(886.1), NoteStr: "A5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15863, Type: dsl.TrackNoteOn, Note: voice.Note(836.0), NoteStr: "G#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15872, Type: dsl.TrackNoteOn, Note: voice.Note(743.4), NoteStr: "F#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15881, Type: dsl.TrackNoteOn, Note: voice.Note(590.2), NoteStr: "D5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15890, Type: dsl.TrackNoteOn, Note: voice.Note(371.7), NoteStr: "F#4", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15899, Type: dsl.TrackNoteOn, Note: voice.Note(590.2), NoteStr: "D5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15908, Type: dsl.TrackNoteOn, Note: voice.Note(743.4), NoteStr: "F#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15918, Type: dsl.TrackNoteOn, Note: voice.Note(836.0), NoteStr: "G#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15927, Type: dsl.TrackNoteOn, Note: voice.Note(886.1), NoteStr: "A5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15936, Type: dsl.TrackNoteOn, Note: voice.Note(836.0), NoteStr: "G#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15945, Type: dsl.TrackNoteOn, Note: voice.Note(743.4), NoteStr: "F#5", Instrument: "adl_148"})
	ch1.AddEvent(dsl.TrackEvent{Tick: 15954, Type: dsl.TrackNoteOn, Note: voice.Note(590.2), NoteStr: "D5", Instrument: "adl_148"})
	ch1.SetInstrumentAt(15963, "adl_145")
	ch1.AddEvent(dsl.TrackEvent{Tick: 15963, Type: dsl.TrackNoteOn, Note: voice.Note(295.1), NoteStr: "D4", Instrument: "adl_145"})
	ch1.NoteOff(16110)
	ch1.SetInstrumentAt(16402, "adl_149")
	ch1.SetInstrumentAt(16548, "adl_145")
	ch1.AddEvent(dsl.TrackEvent{Tick: 16548, Type: dsl.TrackNoteOn, Note: voice.Note(371.7), NoteStr: "F#4", Instrument: "adl_145"})
	ch1.SetInstrumentAt(16695, "adl_149")
	ch1.AddEvent(dsl.TrackEvent{Tick: 16695, Type: dsl.TrackNoteOn, Note: voice.Note(185.9), NoteStr: "F#3", Instrument: "adl_149"})
	ch1.NoteOff(16704)
	ch1.SetInstrumentAt(16841, "adl_145")
	ch1.AddEvent(dsl.TrackEvent{Tick: 16841, Type: dsl.TrackNoteOn, Note: voice.Note(394.5), NoteStr: "G4", Instrument: "adl_145"})
	ch1.SetInstrumentAt(16987, "adl_149")
	ch1.AddEvent(dsl.TrackEvent{Tick: 16987, Type: dsl.TrackNoteOn, Note: voice.Note(197.2), NoteStr: "G3", Instrument: "adl_149"})
	ch1.NoteOff(16996)
	ch1.SetInstrumentAt(17134, "adl_145")
	ch1.AddEvent(dsl.TrackEvent{Tick: 17134, Type: dsl.TrackNoteOn, Note: voice.Note(371.7), NoteStr: "F#4", Instrument: "adl_145"})
	ch1.SetInstrumentAt(17280, "adl_149")
	ch1.AddEvent(dsl.TrackEvent{Tick: 17280, Type: dsl.TrackNoteOn, Note: voice.Note(185.9), NoteStr: "F#3", Instrument: "adl_149"})
	ch1.NoteOff(17289)
	ch1.SetInstrumentAt(17426, "adl_145")
	ch1.AddEvent(dsl.TrackEvent{Tick: 17426, Type: dsl.TrackNoteOn, Note: voice.Note(394.5), NoteStr: "G4", Instrument: "adl_145"})
	ch1.SetInstrumentAt(17572, "adl_149")
	ch1.AddEvent(dsl.TrackEvent{Tick: 17572, Type: dsl.TrackNoteOn, Note: voice.Note(197.2), NoteStr: "G3", Instrument: "adl_149"})
	ch1.NoteOff(17582)
	song.AddTrack(ch1)

	// Channel 2
	ch2 := dsl.NewTrack(2)
	ch2.AddEvent(dsl.TrackEvent{Tick: 0, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_145"})
	ch2.NoteOff(255)
	ch2.AddEvent(dsl.TrackEvent{Tick: 292, Type: dsl.TrackNoteOn, Note: voice.Note(248.8), NoteStr: "B3", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 584, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_145"})
	ch2.NoteOff(840)
	ch2.AddEvent(dsl.TrackEvent{Tick: 877, Type: dsl.TrackNoteOn, Note: voice.Note(248.8), NoteStr: "B3", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 1169, Type: dsl.TrackNoteOn, Note: voice.Note(234.4), NoteStr: "A#3", Instrument: "adl_145"})
	ch2.NoteOff(1316)
	ch2.AddEvent(dsl.TrackEvent{Tick: 1754, Type: dsl.TrackNoteOn, Note: voice.Note(221.5), NoteStr: "A3", Instrument: "adl_145"})
	ch2.NoteOff(1901)
	ch2.AddEvent(dsl.TrackEvent{Tick: 2340, Type: dsl.TrackNoteOn, Note: voice.Note(468.8), NoteStr: "A#4", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 2486, Type: dsl.TrackNoteOn, Note: voice.Note(497.6), NoteStr: "B4", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 2632, Type: dsl.TrackNoteOn, Note: voice.Note(468.8), NoteStr: "A#4", Instrument: "adl_145"})
	ch2.NoteOff(2778)
	ch2.AddEvent(dsl.TrackEvent{Tick: 2925, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 3071, Type: dsl.TrackNoteOn, Note: voice.Note(468.8), NoteStr: "A#4", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 3217, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_145"})
	ch2.NoteOff(3364)
	ch2.AddEvent(dsl.TrackEvent{Tick: 4018, Type: dsl.TrackNoteOn, Note: voice.Note(165.8), NoteStr: "E3", Instrument: "adl_145"})
	ch2.NoteOff(4200)
	ch2.AddEvent(dsl.TrackEvent{Tick: 4443, Type: dsl.TrackNoteOn, Note: voice.Note(185.9), NoteStr: "F#3", Instrument: "adl_145"})
	ch2.NoteOff(4686)
	ch2.AddEvent(dsl.TrackEvent{Tick: 4978, Type: dsl.TrackNoteOn, Note: voice.Note(104.5), NoteStr: "G#2", Instrument: "adl_145"})
	ch2.NoteOff(5271)
	ch2.AddEvent(dsl.TrackEvent{Tick: 5638, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_145"})
	ch2.NoteOff(6005)
	ch2.AddEvent(dsl.TrackEvent{Tick: 6188, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_145"})
	ch2.NoteOff(6371)
	ch2.AddEvent(dsl.TrackEvent{Tick: 6555, Type: dsl.TrackNoteOn, Note: voice.Note(82.9), NoteStr: "E2", Instrument: "adl_145"})
	ch2.SetInstrumentAt(6738, "adl_150")
	ch2.AddEvent(dsl.TrackEvent{Tick: 6738, Type: dsl.TrackNoteOn, Note: voice.Note(62.2), NoteStr: "B1", Instrument: "adl_150"})
	ch2.NoteOff(6843)
	ch2.AddEvent(dsl.TrackEvent{Tick: 6947, Type: dsl.TrackNoteOn, Note: voice.Note(34.9), NoteStr: "C#1", Instrument: "adl_150"})
	ch2.NoteOff(7051)
	ch2.AddEvent(dsl.TrackEvent{Tick: 7155, Type: dsl.TrackNoteOn, Note: voice.Note(62.2), NoteStr: "B1", Instrument: "adl_150"})
	ch2.NoteOff(7259)
	ch2.AddEvent(dsl.TrackEvent{Tick: 7364, Type: dsl.TrackNoteOn, Note: voice.Note(52.2), NoteStr: "G#1", Instrument: "adl_150"})
	ch2.NoteOff(7468)
	ch2.SetInstrumentAt(7572, "adl_145")
	ch2.AddEvent(dsl.TrackEvent{Tick: 7572, Type: dsl.TrackNoteOn, Note: voice.Note(165.8), NoteStr: "E3", Instrument: "adl_145"})
	ch2.NoteOff(7728)
	ch2.AddEvent(dsl.TrackEvent{Tick: 7780, Type: dsl.TrackNoteOn, Note: voice.Note(124.4), NoteStr: "B2", Instrument: "adl_145"})
	ch2.NoteOff(7934)
	ch2.AddEvent(dsl.TrackEvent{Tick: 7985, Type: dsl.TrackNoteOn, Note: voice.Note(156.7), NoteStr: "D#3", Instrument: "adl_145"})
	ch2.NoteOff(8134)
	ch2.AddEvent(dsl.TrackEvent{Tick: 8184, Type: dsl.TrackNoteOn, Note: voice.Note(104.5), NoteStr: "G#2", Instrument: "adl_145"})
	ch2.NoteOff(8473)
	ch2.SetInstrumentAt(8925, "adl_151")
	ch2.AddEvent(dsl.TrackEvent{Tick: 8925, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_151"})
	ch2.NoteOff(8947)
	ch2.AddEvent(dsl.TrackEvent{Tick: 9364, Type: dsl.TrackNoteOn, Note: voice.Note(331.5), NoteStr: "E4", Instrument: "adl_151"})
	ch2.NoteOff(9385)
	ch2.AddEvent(dsl.TrackEvent{Tick: 9577, Type: dsl.TrackNoteOn, Note: voice.Note(497.6), NoteStr: "B4", Instrument: "adl_151"})
	ch2.NoteOff(9598)
	ch2.AddEvent(dsl.TrackEvent{Tick: 9619, Type: dsl.TrackNoteOn, Note: voice.Note(526.5), NoteStr: "C5", Instrument: "adl_151"})
	ch2.NoteOff(9640)
	ch2.SetInstrumentAt(13168, "adl_145")
	ch2.AddEvent(dsl.TrackEvent{Tick: 13168, Type: dsl.TrackNoteOn, Note: voice.Note(165.8), NoteStr: "E3", Instrument: "adl_145"})
	ch2.NoteOff(13321)
	ch2.AddEvent(dsl.TrackEvent{Tick: 13473, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_145"})
	ch2.NoteOff(13622)
	ch2.AddEvent(dsl.TrackEvent{Tick: 13915, Type: dsl.TrackNoteOn, Note: voice.Note(331.5), NoteStr: "E4", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 14061, Type: dsl.TrackNoteOn, Note: voice.Note(313.3), NoteStr: "D#4", Instrument: "adl_145"})
	ch2.NoteOff(14208)
	ch2.AddEvent(dsl.TrackEvent{Tick: 14500, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 14573, Type: dsl.TrackNoteOn, Note: voice.Note(209.0), NoteStr: "G#3", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 14646, Type: dsl.TrackNoteOn, Note: voice.Note(221.5), NoteStr: "A3", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 14720, Type: dsl.TrackNoteOn, Note: voice.Note(185.9), NoteStr: "F#3", Instrument: "adl_145"})
	ch2.NoteOff(14793)
	ch2.AddEvent(dsl.TrackEvent{Tick: 15085, Type: dsl.TrackNoteOn, Note: voice.Note(331.5), NoteStr: "E4", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 15232, Type: dsl.TrackNoteOn, Note: voice.Note(313.3), NoteStr: "D#4", Instrument: "adl_145"})
	ch2.NoteOff(15378)
	ch2.AddEvent(dsl.TrackEvent{Tick: 15670, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 15744, Type: dsl.TrackNoteOn, Note: voice.Note(197.2), NoteStr: "G3", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 15817, Type: dsl.TrackNoteOn, Note: voice.Note(221.5), NoteStr: "A3", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 15890, Type: dsl.TrackNoteOn, Note: voice.Note(295.1), NoteStr: "D4", Instrument: "adl_145"})
	ch2.AddEvent(dsl.TrackEvent{Tick: 15963, Type: dsl.TrackNoteOn, Note: voice.Note(371.7), NoteStr: "F#4", Instrument: "adl_145"})
	ch2.NoteOff(16109)
	ch2.SetInstrumentAt(16402, "adl_149")
	ch2.SetInstrumentAt(16548, "adl_145")
	ch2.AddEvent(dsl.TrackEvent{Tick: 16548, Type: dsl.TrackNoteOn, Note: voice.Note(295.1), NoteStr: "D4", Instrument: "adl_145"})
	ch2.SetInstrumentAt(16694, "adl_149")
	ch2.AddEvent(dsl.TrackEvent{Tick: 16694, Type: dsl.TrackNoteOn, Note: voice.Note(147.5), NoteStr: "D3", Instrument: "adl_149"})
	ch2.NoteOff(16704)
	ch2.SetInstrumentAt(16841, "adl_145")
	ch2.AddEvent(dsl.TrackEvent{Tick: 16841, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_145"})
	ch2.SetInstrumentAt(16987, "adl_149")
	ch2.AddEvent(dsl.TrackEvent{Tick: 16987, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_149"})
	ch2.NoteOff(16996)
	ch2.SetInstrumentAt(17133, "adl_145")
	ch2.AddEvent(dsl.TrackEvent{Tick: 17133, Type: dsl.TrackNoteOn, Note: voice.Note(295.1), NoteStr: "D4", Instrument: "adl_145"})
	ch2.SetInstrumentAt(17280, "adl_149")
	ch2.AddEvent(dsl.TrackEvent{Tick: 17280, Type: dsl.TrackNoteOn, Note: voice.Note(147.5), NoteStr: "D3", Instrument: "adl_149"})
	ch2.NoteOff(17289)
	ch2.SetInstrumentAt(17426, "adl_145")
	ch2.AddEvent(dsl.TrackEvent{Tick: 17426, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_145"})
	ch2.SetInstrumentAt(17572, "adl_149")
	ch2.AddEvent(dsl.TrackEvent{Tick: 17572, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_149"})
	ch2.NoteOff(17581)
	song.AddTrack(ch2)

	// Channel 3
	ch3 := dsl.NewTrack(3)
	ch3.AddEvent(dsl.TrackEvent{Tick: 584, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_152"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 877, Type: dsl.TrackNoteOn, Note: voice.Note(248.8), NoteStr: "B3", Instrument: "adl_152"})
	ch3.SetInstrumentAt(1169, "adl_153")
	ch3.AddEvent(dsl.TrackEvent{Tick: 1169, Type: dsl.TrackNoteOn, Note: voice.Note(117.2), NoteStr: "A#2", Instrument: "adl_153"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 1754, Type: dsl.TrackNoteOn, Note: voice.Note(110.8), NoteStr: "A2", Instrument: "adl_153"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 2340, Type: dsl.TrackNoteOn, Note: voice.Note(117.2), NoteStr: "A#2", Instrument: "adl_153"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 2925, Type: dsl.TrackNoteOn, Note: voice.Note(110.8), NoteStr: "A2", Instrument: "adl_153"})
	ch3.NoteOff(3510)
	ch3.SetInstrumentAt(3673, "adl_154")
	ch3.AddEvent(dsl.TrackEvent{Tick: 3673, Type: dsl.TrackNoteOn, Note: voice.Note(1772.1), NoteStr: "A6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3683, Type: dsl.TrackNoteOn, Note: voice.Note(1672.0), NoteStr: "G#6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3693, Type: dsl.TrackNoteOn, Note: voice.Note(1577.9), NoteStr: "G6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3703, Type: dsl.TrackNoteOn, Note: voice.Note(1486.9), NoteStr: "F#6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3713, Type: dsl.TrackNoteOn, Note: voice.Note(1404.9), NoteStr: "F6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3723, Type: dsl.TrackNoteOn, Note: voice.Note(1326.0), NoteStr: "E6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3734, Type: dsl.TrackNoteOn, Note: voice.Note(1253.2), NoteStr: "D#6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3744, Type: dsl.TrackNoteOn, Note: voice.Note(1180.4), NoteStr: "D6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3754, Type: dsl.TrackNoteOn, Note: voice.Note(1116.7), NoteStr: "C#6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3764, Type: dsl.TrackNoteOn, Note: voice.Note(1052.9), NoteStr: "C6", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3774, Type: dsl.TrackNoteOn, Note: voice.Note(995.3), NoteStr: "B5", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3785, Type: dsl.TrackNoteOn, Note: voice.Note(937.6), NoteStr: "A#5", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3795, Type: dsl.TrackNoteOn, Note: voice.Note(886.1), NoteStr: "A5", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3805, Type: dsl.TrackNoteOn, Note: voice.Note(836.0), NoteStr: "G#5", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3815, Type: dsl.TrackNoteOn, Note: voice.Note(789.0), NoteStr: "G5", Instrument: "adl_154"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 3825, Type: dsl.TrackNoteOn, Note: voice.Note(743.4), NoteStr: "F#5", Instrument: "adl_154"})
	ch3.NoteOff(3835)
	ch3.AddEvent(dsl.TrackEvent{Tick: 4063, Type: dsl.TrackNoteOn, Note: voice.Note(1772.1), NoteStr: "A6", Instrument: "adl_154"})
	ch3.NoteOff(4074)
	ch3.AddEvent(dsl.TrackEvent{Tick: 4154, Type: dsl.TrackNoteOn, Note: voice.Note(1577.9), NoteStr: "G6", Instrument: "adl_154"})
	ch3.NoteOff(4165)
	ch3.AddEvent(dsl.TrackEvent{Tick: 4321, Type: dsl.TrackNoteOn, Note: voice.Note(1772.1), NoteStr: "A6", Instrument: "adl_154"})
	ch3.NoteOff(4336)
	ch3.AddEvent(dsl.TrackEvent{Tick: 4503, Type: dsl.TrackNoteOn, Note: voice.Note(1672.0), NoteStr: "G#6", Instrument: "adl_154"})
	ch3.NoteOff(4518)
	ch3.AddEvent(dsl.TrackEvent{Tick: 4759, Type: dsl.TrackNoteOn, Note: voice.Note(1326.0), NoteStr: "E6", Instrument: "adl_154"})
	ch3.NoteOff(4777)
	ch3.AddEvent(dsl.TrackEvent{Tick: 5051, Type: dsl.TrackNoteOn, Note: voice.Note(1253.2), NoteStr: "D#6", Instrument: "adl_154"})
	ch3.NoteOff(5070)
	ch3.AddEvent(dsl.TrackEvent{Tick: 5546, Type: dsl.TrackNoteOn, Note: voice.Note(995.3), NoteStr: "B5", Instrument: "adl_154"})
	ch3.NoteOff(5569)
	ch3.AddEvent(dsl.TrackEvent{Tick: 5821, Type: dsl.TrackNoteOn, Note: voice.Note(1875.3), NoteStr: "A#6", Instrument: "adl_154"})
	ch3.NoteOff(5844)
	ch3.AddEvent(dsl.TrackEvent{Tick: 6004, Type: dsl.TrackNoteOn, Note: voice.Note(1772.1), NoteStr: "A6", Instrument: "adl_154"})
	ch3.NoteOff(6027)
	ch3.AddEvent(dsl.TrackEvent{Tick: 6646, Type: dsl.TrackNoteOn, Note: voice.Note(1404.9), NoteStr: "F6", Instrument: "adl_154"})
	ch3.NoteOff(6669)
	ch3.AddEvent(dsl.TrackEvent{Tick: 6738, Type: dsl.TrackNoteOn, Note: voice.Note(497.6), NoteStr: "B4", Instrument: "adl_154"})
	ch3.NoteOff(6752)
	ch3.AddEvent(dsl.TrackEvent{Tick: 6843, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_154"})
	ch3.NoteOff(6856)
	ch3.AddEvent(dsl.TrackEvent{Tick: 6895, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_154"})
	ch3.NoteOff(6908)
	ch3.AddEvent(dsl.TrackEvent{Tick: 6947, Type: dsl.TrackNoteOn, Note: voice.Note(558.3), NoteStr: "C#5", Instrument: "adl_154"})
	ch3.NoteOff(6960)
	ch3.AddEvent(dsl.TrackEvent{Tick: 7051, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_154"})
	ch3.NoteOff(7064)
	ch3.AddEvent(dsl.TrackEvent{Tick: 7155, Type: dsl.TrackNoteOn, Note: voice.Note(443.0), NoteStr: "A4", Instrument: "adl_154"})
	ch3.NoteOff(7168)
	ch3.AddEvent(dsl.TrackEvent{Tick: 7259, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_154"})
	ch3.NoteOff(7272)
	ch3.AddEvent(dsl.TrackEvent{Tick: 7311, Type: dsl.TrackNoteOn, Note: voice.Note(371.7), NoteStr: "F#4", Instrument: "adl_154"})
	ch3.NoteOff(7324)
	ch3.AddEvent(dsl.TrackEvent{Tick: 7363, Type: dsl.TrackNoteOn, Note: voice.Note(313.3), NoteStr: "D#4", Instrument: "adl_154"})
	ch3.NoteOff(7377)
	ch3.AddEvent(dsl.TrackEvent{Tick: 7468, Type: dsl.TrackNoteOn, Note: voice.Note(331.5), NoteStr: "E4", Instrument: "adl_154"})
	ch3.NoteOff(7481)
	ch3.AddEvent(dsl.TrackEvent{Tick: 7520, Type: dsl.TrackNoteOn, Note: voice.Note(313.3), NoteStr: "D#4", Instrument: "adl_154"})
	ch3.NoteOff(7533)
	ch3.SetInstrumentAt(7572, "adl_155")
	ch3.AddEvent(dsl.TrackEvent{Tick: 7572, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 7780, Type: dsl.TrackNoteOn, Note: voice.Note(248.8), NoteStr: "B3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 8184, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 8565, Type: dsl.TrackNoteOn, Note: voice.Note(197.2), NoteStr: "G3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 8925, Type: dsl.TrackNoteOn, Note: voice.Note(185.9), NoteStr: "F#3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 9278, Type: dsl.TrackNoteOn, Note: voice.Note(165.8), NoteStr: "E3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 9619, Type: dsl.TrackNoteOn, Note: voice.Note(156.7), NoteStr: "D#3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 9953, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 10117, Type: dsl.TrackNoteOn, Note: voice.Note(165.8), NoteStr: "E3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 10199, Type: dsl.TrackNoteOn, Note: voice.Note(156.7), NoteStr: "D#3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 10281, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 10445, Type: dsl.TrackNoteOn, Note: voice.Note(221.5), NoteStr: "A3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 10609, Type: dsl.TrackNoteOn, Note: voice.Note(165.8), NoteStr: "E3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 10772, Type: dsl.TrackNoteOn, Note: voice.Note(156.7), NoteStr: "D#3", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 10936, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_155"})
	ch3.NoteOff(11425)
	ch3.AddEvent(dsl.TrackEvent{Tick: 11826, Type: dsl.TrackNoteOn, Note: voice.Note(104.5), NoteStr: "G#2", Instrument: "adl_155"})
	ch3.NoteOff(11987)
	ch3.AddEvent(dsl.TrackEvent{Tick: 12067, Type: dsl.TrackNoteOn, Note: voice.Note(139.6), NoteStr: "C#3", Instrument: "adl_155"})
	ch3.NoteOff(12305)
	ch3.AddEvent(dsl.TrackEvent{Tick: 12384, Type: dsl.TrackNoteOn, Note: voice.Note(147.5), NoteStr: "D3", Instrument: "adl_155"})
	ch3.NoteOff(12699)
	ch3.AddEvent(dsl.TrackEvent{Tick: 12857, Type: dsl.TrackNoteOn, Note: voice.Note(124.4), NoteStr: "B2", Instrument: "adl_155"})
	ch3.AddEvent(dsl.TrackEvent{Tick: 13168, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_155"})
	ch3.NoteOff(13473)
	ch3.SetInstrumentAt(13915, "adl_156")
	ch3.AddEvent(dsl.TrackEvent{Tick: 13915, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_156"})
	ch3.NoteOff(13924)
	ch3.AddEvent(dsl.TrackEvent{Tick: 14500, Type: dsl.TrackNoteOn, Note: voice.Note(663.0), NoteStr: "E5", Instrument: "adl_156"})
	ch3.NoteOff(14509)
	ch3.AddEvent(dsl.TrackEvent{Tick: 14573, Type: dsl.TrackNoteOn, Note: voice.Note(836.0), NoteStr: "G#5", Instrument: "adl_156"})
	ch3.NoteOff(14582)
	ch3.AddEvent(dsl.TrackEvent{Tick: 14646, Type: dsl.TrackNoteOn, Note: voice.Note(886.1), NoteStr: "A5", Instrument: "adl_156"})
	ch3.NoteOff(14655)
	ch3.AddEvent(dsl.TrackEvent{Tick: 15085, Type: dsl.TrackNoteOn, Note: voice.Note(418.0), NoteStr: "G#4", Instrument: "adl_156"})
	ch3.NoteOff(15094)
	ch3.AddEvent(dsl.TrackEvent{Tick: 15231, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_156"})
	ch3.NoteOff(15241)
	ch3.AddEvent(dsl.TrackEvent{Tick: 15670, Type: dsl.TrackNoteOn, Note: voice.Note(626.6), NoteStr: "D#5", Instrument: "adl_156"})
	ch3.NoteOff(15679)
	ch3.AddEvent(dsl.TrackEvent{Tick: 15743, Type: dsl.TrackNoteOn, Note: voice.Note(789.0), NoteStr: "G5", Instrument: "adl_156"})
	ch3.NoteOff(15753)
	ch3.AddEvent(dsl.TrackEvent{Tick: 15817, Type: dsl.TrackNoteOn, Note: voice.Note(590.2), NoteStr: "D5", Instrument: "adl_156"})
	ch3.NoteOff(15826)
	ch3.AddEvent(dsl.TrackEvent{Tick: 15963, Type: dsl.TrackNoteOn, Note: voice.Note(995.3), NoteStr: "B5", Instrument: "adl_156"})
	ch3.NoteOff(15972)
	ch3.SetInstrumentAt(16548, "adl_149")
	ch3.AddEvent(dsl.TrackEvent{Tick: 16694, Type: dsl.TrackNoteOn, Note: voice.Note(248.8), NoteStr: "B3", Instrument: "adl_149"})
	ch3.NoteOff(16703)
	ch3.AddEvent(dsl.TrackEvent{Tick: 16987, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_149"})
	ch3.NoteOff(16996)
	ch3.AddEvent(dsl.TrackEvent{Tick: 17279, Type: dsl.TrackNoteOn, Note: voice.Note(248.8), NoteStr: "B3", Instrument: "adl_149"})
	ch3.NoteOff(17289)
	ch3.AddEvent(dsl.TrackEvent{Tick: 17572, Type: dsl.TrackNoteOn, Note: voice.Note(279.2), NoteStr: "C#4", Instrument: "adl_149"})
	ch3.NoteOff(17581)
	song.AddTrack(ch3)

	// Channel 4
	ch4 := dsl.NewTrack(4)
	ch4.AddEvent(dsl.TrackEvent{Tick: 566, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_157"})
	ch4.NoteOff(593)
	ch4.AddEvent(dsl.TrackEvent{Tick: 1151, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_157"})
	ch4.NoteOff(1178)
	ch4.AddEvent(dsl.TrackEvent{Tick: 1754, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_157"})
	ch4.NoteOff(1764)
	ch4.AddEvent(dsl.TrackEvent{Tick: 2340, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_157"})
	ch4.NoteOff(2349)
	ch4.AddEvent(dsl.TrackEvent{Tick: 2925, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_157"})
	ch4.NoteOff(2934)
	ch4.SetInstrumentAt(6738, "adl_158")
	ch4.AddEvent(dsl.TrackEvent{Tick: 6738, Type: dsl.TrackNoteOn, Note: voice.Note(24.7), NoteStr: "G0", Instrument: "adl_158"})
	ch4.NoteOff(6752)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7155, Type: dsl.TrackNoteOn, Note: voice.Note(24.7), NoteStr: "G0", Instrument: "adl_158"})
	ch4.NoteOff(7168)
	ch4.SetInstrumentAt(7572, "adl_159")
	ch4.AddEvent(dsl.TrackEvent{Tick: 7572, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7585)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7598, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7611)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7624, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7637)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7650, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7663)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7676, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7689)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7702, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7715)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7728, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7741)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7754, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7767)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7780, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7793)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7806, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7819)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7832, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7845)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7857, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7870)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7883, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7896)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7909, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7921)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7934, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7947)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7959, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7972)
	ch4.AddEvent(dsl.TrackEvent{Tick: 7985, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(7997)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8010, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8022)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8035, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8047)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8060, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8072)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8085, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8097)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8110, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8122)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8134, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8147)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8159, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8171)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8184, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8196)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8208, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8245)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8257, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8269)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8281, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8293)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8305, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8317)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8329, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8365)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8377, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8389)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8401, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8413)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8425, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8437)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8449, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8484)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8496, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8530)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8542, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8554)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8565, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8576)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8588, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8599)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8611, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8622)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8633, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8667)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8679, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8690)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8702, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8713)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8724, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8736)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8747, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8758)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8769, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8781)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8792, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8803)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8814, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8825)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8836, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8870)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8881, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8892)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8903, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8914)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8925, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8936)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8947, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(8959)
	ch4.AddEvent(dsl.TrackEvent{Tick: 8970, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9003)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9014, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9048)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9059, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9092)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9103, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9158)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9169, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9180)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9190, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9201)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9212, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9267)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9278, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9288)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9299, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9310)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9321, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9374)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9385, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9439)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9449, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9460)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9471, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9502)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9513, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9524)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9534, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9566)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9577, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9672)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9682, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9756)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9766, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9891)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9901, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9922)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9933, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(9943)
	ch4.AddEvent(dsl.TrackEvent{Tick: 9953, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10189)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10199, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10209)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10220, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10230)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10240, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10373)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10383, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10394)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10404, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10455)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10465, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10476)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10486, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10517)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10527, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10558)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10568, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10598)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10609, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10639)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10650, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10680)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10691, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10721)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10732, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10762)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10773, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10885)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10895, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(10967)
	ch4.AddEvent(dsl.TrackEvent{Tick: 10977, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(11150)
	ch4.AddEvent(dsl.TrackEvent{Tick: 11160, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(11191)
	ch4.AddEvent(dsl.TrackEvent{Tick: 11201, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(11313)
	ch4.AddEvent(dsl.TrackEvent{Tick: 11323, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(11333)
	ch4.AddEvent(dsl.TrackEvent{Tick: 11343, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(11415)
	ch4.AddEvent(dsl.TrackEvent{Tick: 11425, Type: dsl.TrackNoteOn, Note: voice.Note(263.2), NoteStr: "C4", Instrument: "adl_159"})
	ch4.NoteOff(13915)
	song.AddTrack(ch4)

	// Channel 5
	ch5 := dsl.NewTrack(5)
	ch5.AddEvent(dsl.TrackEvent{Tick: 0, Type: dsl.TrackNoteOn, Note: voice.Note(92.9), NoteStr: "F#2", Instrument: "adl_147"})
	ch5.AddEvent(dsl.TrackEvent{Tick: 292, Type: dsl.TrackNoteOn, Note: voice.Note(82.9), NoteStr: "E2", Instrument: "adl_147"})
	ch5.AddEvent(dsl.TrackEvent{Tick: 584, Type: dsl.TrackNoteOn, Note: voice.Note(92.9), NoteStr: "F#2", Instrument: "adl_147"})
	ch5.AddEvent(dsl.TrackEvent{Tick: 877, Type: dsl.TrackNoteOn, Note: voice.Note(82.9), NoteStr: "E2", Instrument: "adl_147"})
	ch5.AddEvent(dsl.TrackEvent{Tick: 1169, Type: dsl.TrackNoteOn, Note: voice.Note(78.3), NoteStr: "D#2", Instrument: "adl_147"})
	ch5.AddEvent(dsl.TrackEvent{Tick: 1754, Type: dsl.TrackNoteOn, Note: voice.Note(73.8), NoteStr: "D2", Instrument: "adl_147"})
	ch5.AddEvent(dsl.TrackEvent{Tick: 2340, Type: dsl.TrackNoteOn, Note: voice.Note(78.3), NoteStr: "D#2", Instrument: "adl_147"})
	ch5.AddEvent(dsl.TrackEvent{Tick: 2925, Type: dsl.TrackNoteOn, Note: voice.Note(73.8), NoteStr: "D2", Instrument: "adl_147"})
	ch5.NoteOff(3510)
	ch5.SetInstrumentAt(3835, "adl_150")
	ch5.AddEvent(dsl.TrackEvent{Tick: 3835, Type: dsl.TrackNoteOn, Note: voice.Note(69.8), NoteStr: "C#2", Instrument: "adl_150"})
	ch5.NoteOff(4108)
	ch5.AddEvent(dsl.TrackEvent{Tick: 4321, Type: dsl.TrackNoteOn, Note: voice.Note(55.4), NoteStr: "A1", Instrument: "adl_150"})
	ch5.NoteOff(4564)
	ch5.AddEvent(dsl.TrackEvent{Tick: 4978, Type: dsl.TrackNoteOn, Note: voice.Note(34.9), NoteStr: "C#1", Instrument: "adl_150"})
	ch5.NoteOff(5271)
	ch5.AddEvent(dsl.TrackEvent{Tick: 5637, Type: dsl.TrackNoteOn, Note: voice.Note(31.1), NoteStr: "B0", Instrument: "adl_150"})
	ch5.NoteOff(5821)
	ch5.AddEvent(dsl.TrackEvent{Tick: 11746, Type: dsl.TrackNoteOn, Note: voice.Note(34.9), NoteStr: "C#1", Instrument: "adl_150"})
	ch5.NoteOff(12067)
	ch5.AddEvent(dsl.TrackEvent{Tick: 12384, Type: dsl.TrackNoteOn, Note: voice.Note(49.3), NoteStr: "G1", Instrument: "adl_150"})
	ch5.NoteOff(12699)
	ch5.AddEvent(dsl.TrackEvent{Tick: 15963, Type: dsl.TrackNoteOn, Note: voice.Note(62.2), NoteStr: "B1", Instrument: "adl_150"})
	ch5.NoteOff(16255)
	song.AddTrack(ch5)

	return song
}

// PlayDUNE1 creates a stream and plays the song.
// Returns the stream for use with audio output.
func PlayDUNE1(st *stream.Stream) error {
	song := NewDUNE1Song6()
	return song.Play(st)
}
